/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fusionapp;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import weka.core.Instances;

/**
 *
 * @author ZeytoonCo
 */
public class Fram2Fusion extends javax.swing.JFrame {
String fusionTechniques ="Majority Voting";
String windowType = "Window with increasing size";
String fileName =null;
Fusion f = null;
    private int winSize=2;
    /**
     * Creates new form Fram2Fusion
     */
    public Fram2Fusion(String fileNam, Fusion ff) {
        this.fileName = fileNam;
        f = ff;
        initComponents();
    }
public Fram2Fusion(){

}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fusioncombo = new javax.swing.JComboBox<>();
        windowCombo = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        calcButt = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        AccuracyText = new javax.swing.JTextArea();
        finishButt = new javax.swing.JButton();
        winSizeComb = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fusioncombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Majority Voting", "Sum rule", " " }));
        fusioncombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fusioncomboActionPerformed(evt);
            }
        });

        windowCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Window with increasing size", "Window with decreasing size", "Window with fixed size" }));
        windowCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowComboActionPerformed(evt);
            }
        });

        jTextField1.setText("Please choose Fusion technique and the Type of Window-based classification");

        calcButt.setText("Calculate");
        calcButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcButtActionPerformed(evt);
            }
        });

        AccuracyText.setColumns(20);
        AccuracyText.setRows(5);
        jScrollPane1.setViewportView(AccuracyText);

        finishButt.setText("Fininsh");

        winSizeComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4", "5", "6" }));
        winSizeComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winSizeCombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fusioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(windowCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(winSizeComb, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)))
                        .addComponent(calcButt, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(finishButt)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(windowCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fusioncombo, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(calcButt, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(winSizeComb, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(finishButt)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fusioncomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fusioncomboActionPerformed
        // TODO add your handling code here:
     fusionTechniques =   fusioncombo.getItemAt(fusioncombo.getSelectedIndex());  
    }//GEN-LAST:event_fusioncomboActionPerformed

    private void windowComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowComboActionPerformed
        // TODO add your handling code here:
        windowType = windowCombo.getItemAt(windowCombo.getSelectedIndex());
        
    }//GEN-LAST:event_windowComboActionPerformed

    private void calcButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcButtActionPerformed
          BufferedReader reader = null;
          String text="";
    try {
        // TODO add your handling code here:
        reader = new BufferedReader(new FileReader(fileName));
        Instances data = new Instances(reader);
        reader.close();
        data.setClassIndex(data.numAttributes() - 1);
       
        if(windowType.equals("Window with increasing size")){
            if(fusionTechniques.equals("Majority Voting")){
             
                text = f.IncreaseFusionCrossValidationMV(  "D:\\pred", data,winSize);
            }else{
                text = f.IncreaseFusionCrossValidationSum(  "D:\\pred", data,winSize);
            }
        }else if(windowType.equals("Window with decreasing size")){
            if(fusionTechniques.equals("Majority Voting")){
                text = f.DecreaseFusionCrossValidationMV(  "D:\\pred", data,winSize,0);
            }else{
                text = f.DecreaseFusionCrossValidationSum(  "D:\\pred", data,winSize,0);
            }
    }
        else{
              if(fusionTechniques.equals("Majority Voting")){
                text = f.FixedFusionCrossValidationMV(  "D:\\pred", data,winSize);
            }else{
                text = f.FixedFusionCrossValidationSum(  "D:\\pred", data,winSize);
            }
        }
    } catch (FileNotFoundException ex) {
        Logger.getLogger(Fram2Fusion.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(Fram2Fusion.class.getName()).log(Level.SEVERE, null, ex);
    } finally {
        try {
            reader.close();
        } catch (IOException ex) {
            Logger.getLogger(Fram2Fusion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
        AccuracyText.setText(windowType + " with size " + winSize+ " ----"+ fusionTechniques+" ------\n" + text);
    }//GEN-LAST:event_calcButtActionPerformed

    private void winSizeCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winSizeCombActionPerformed
        // TODO add your handling code here:
        String s =winSizeComb.getItemAt(winSizeComb.getSelectedIndex());
        winSize = Integer.parseInt(s);
    }//GEN-LAST:event_winSizeCombActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fram2Fusion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fram2Fusion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fram2Fusion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fram2Fusion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fram2Fusion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AccuracyText;
    private javax.swing.JButton calcButt;
    private javax.swing.JButton finishButt;
    private javax.swing.JComboBox<String> fusioncombo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox<String> winSizeComb;
    private javax.swing.JComboBox<String> windowCombo;
    // End of variables declaration//GEN-END:variables
}
